# Pioneer3at Velocity Controllers ---------------------------------------

pioneer3at_left_front_wheel_controller:
  type: effort_controllers/JointVelocityController
  joint: p3at_front_left_wheel_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}

pioneer3at_left_rear_wheel_controller:
  type: effort_controllers/JointVelocityController
  joint: p3at_back_left_wheel_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}
  
pioneer3at_right_front_wheel_controller:
  type: effort_controllers/JointVelocityController
  joint: p3at_front_right_wheel_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}

pioneer3at_right_rear_wheel_controller:
  type: effort_controllers/JointVelocityController
  joint: p3at_back_right_wheel_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}
