# Linear Head Position Controllers ---------------------------------------

linear_head_pitch_controller:
  type: effort_controllers/JointPositionController
  joint: linear_head_pitch_joint
  pid: {p: 11.0, i: 2.0, d: 0.25, i_clamp: 15.0}

linear_head_yaw_controller:
  type: effort_controllers/JointPositionController
  joint: linear_head_yaw_joint
  pid: {p: 12.0, i: 1.0, d: 0.45, i_clamp: 10.0}
