# Linear Elevator Position Controller -----------------------------------

linear_elevator_controller:
  type: effort_controllers/JointPositionController
  joint: linear_elevator_joint
  pid: {p: 90.0, i: 5.0, d: 20.0, i_clamp: 100.0}
