# Linear Elevator Position Controller -----------------------------------

linear_elevator_controller:
  type: effort_controllers/JointPositionController
  joint: linear_elevator_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}
