# Kinect Position Controllers ---------------------------------------

kinect_pitch_controller:
  type: effort_controllers/JointPositionController
  joint: kinect_pitch_joint
  pid: {p: 1.2, i: 0.0, d: 0.5}

kinect_yaw_controller:
  type: effort_controllers/JointPositionController
  joint: kinect_yaw_joint
  pid: {p: 0.8, i: 0.0, d: 0.45}
