# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

# Position Controllers ---------------------------------------
laser_roll_controller:
  type: effort_controllers/JointPositionController
  joint: laser_roll_joint
  pid: {p: 1.8, i: 0.0, d: 0.45}

laser_pitch_controller:
  type: effort_controllers/JointPositionController
  joint: laser_pitch_joint
  pid: {p: 2.5, i: 0.0, d: 0.3}

kinect_pitch_controller:
  type: effort_controllers/JointPositionController
  joint: kinect_pitch_joint
  pid: {p: 1.2, i: 0.0, d: 0.5}

kinect_yaw_controller:
  type: effort_controllers/JointPositionController
  joint: kinect_yaw_joint
  pid: {p: 0.8, i: 0.0, d: 0.45}
  

