# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

# Position Controllers ---------------------------------------
laser_roll_controller:
  type: effort_controllers/JointPositionController
  joint: laser_roll_joint
  pid: {p: 1.0, i: 0.01, d: 0.1}

laser_pitch_controller:
  type: effort_controllers/JointPositionController
  joint: laser_pitch_joint
  pid: {p: 1.0, i: 0.01, d: 0.1}

kinect_pitch_controller:
  type: effort_controllers/JointPositionController
  joint: kinect_pitch_joint
  pid: {p: 1.0, i: 0.01, d: 0.1}

kinect_yaw_controller:
  type: effort_controllers/JointPositionController
  joint: kinect_yaw_joint
  pid: {p: 1.0, i: 0.01, d: 0.1}
  

