# Kinect Position Controllers ---------------------------------------

kinect_pitch_controller:
  type: effort_controllers/JointPositionController
  joint: kinect_pitch_joint
  pid: {p: 8.5, i: 1.0, d: 0.2, i_clamp: 10.0}

kinect_yaw_controller:
  type: effort_controllers/JointPositionController
  joint: kinect_yaw_joint
  pid: {p: 8.0, i: 1.5, d: 0.4, i_clamp: 10.0}
