# Pioneer3at Velocity Controllers ---------------------------------------
p3at_front_left_wheel_controller:
  type: velocity_controllers/JointVelocityController
  joint: p3at_front_left_wheel_joint
  pid: &p3at_wheel_velocity_gains
    p: 0.0
    i: 0.0
    d: 0.0
    i_clamp: 0.0

p3at_front_right_wheel_controller:
  type: velocity_controllers/JointVelocityController
  joint: p3at_front_right_wheel_joint
  pid: *p3at_wheel_velocity_gains

p3at_back_left_wheel_controller:
  type: velocity_controllers/JointVelocityController
  joint: p3at_back_left_wheel_joint
  pid: *p3at_wheel_velocity_gains

p3at_back_right_wheel_controller:
  type: velocity_controllers/JointVelocityController
  joint: p3at_back_right_wheel_joint
  pid: *p3at_wheel_velocity_gains
