# Laser Position Controllers ---------------------------------------

laser_roll_controller:
  type: effort_controllers/JointPositionController
  joint: laser_roll_joint
  pid: {p: 9.0, i: 1.8, d: 2.0, i_clamp: 0.0}

laser_pitch_controller:
  type: effort_controllers/JointPositionController
  joint: laser_pitch_joint
  pid: {p: 9.0, i: 0.0, d: 0.3, i_clamp: 0.0}
